# Generated by Django 5.0.3 on 2024-03-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Journal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("cost", models.DecimalField(decimal_places=2, max_digits=7)),
                ("destination", models.CharField(max_length=255)),
                ("description", models.TextField()),
            ],
        ),
    ]
