# Generated by Django 5.0.3 on 2024-03-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journal",
            name="end_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="journal",
            name="start_date",
            field=models.DateField(),
        ),
    ]
