# Generated by Django 5.0.3 on 2024-03-21 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0002_alter_journal_end_date_alter_journal_start_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="journal",
            old_name="cost",
            new_name="estimated_cost",
        ),
        migrations.RenameField(
            model_name="journal",
            old_name="destination",
            new_name="from_to",
        ),
        migrations.CreateModel(
            name="Itinerary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("point_a", models.CharField(max_length=255)),
                ("point_b", models.CharField(max_length=255)),
                ("estimated_hrs", models.CharField(max_length=2)),
                (
                    "journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="journal.journal",
                    ),
                ),
            ],
        ),
    ]
