# Generated by Django 5.0.3 on 2024-03-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0004_itinerary_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="itinerary",
            name="description",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
