# Generated by Django 5.0.3 on 2024-03-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0007_images_delete_journalimages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itinerary",
            name="estimated_hrs",
            field=models.CharField(max_length=3),
        ),
    ]
