# Generated by Django 5.0.3 on 2024-03-22 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0008_alter_itinerary_estimated_hrs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="images",
            name="journal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="image",
                to="journal.journal",
            ),
        ),
        migrations.AlterField(
            model_name="itinerary",
            name="journal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="itinerary",
                to="journal.journal",
            ),
        ),
    ]
