# Generated by Django 5.0.3 on 2024-03-22 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0009_alter_images_journal_alter_itinerary_journal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="images",
            name="image",
            field=models.ImageField(upload_to="images"),
        ),
    ]
