# Generated by Django 4.1 on 2024-07-11 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signal_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CustomUser',
        ),
    ]
