# Generated by Django 4.1 on 2024-07-11 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signal_app', '0002_rename_user_customuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='User',
        ),
    ]
