# Generated by Django 4.1 on 2024-07-11 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signal_app', '0005_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='signal_app.customuser'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=150)),
                ('blogpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signal_app.blogpost')),
                ('comment_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signal_app.customuser')),
            ],
        ),
    ]
